{
 "title": "Loki Operator Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_build_info{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"})"
    }
   ]
  },
  {
   "title": "Alerts Event Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cortex_prometheus_notifications_sent_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_prometheus_rule_group_rules{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"})"
    }
   ]
  },
  {
   "title": "Internal Panics (rate)",
   "type": "timeseries",
   "description": "Rate of Go panic errors produced by Loki",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by(juju_application) (rate(loki_panic_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Log Messages (rate)",
   "type": "timeseries",
   "description": "Rate of log messages produced by Loki itself",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by(level) (rate(loki_internal_log_messages_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Ingested Logs (uncompressed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Ingested Logs (by size)",
   "type": "heatmap",
   "description": "Each row corresponds to the size of ingested log lines.\nHover over the cells to see the exact bucket: logs whose size fits in that bucket will be counted there.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(le) (increase(loki_bytes_per_line_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "timeseries",
   "description": "Each time series shows the 95th-percentile (the maximum latency for *most* requests)",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, route) (rate(loki_request_duration_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) != 0))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Ingester Requests Latency",
   "type": "timeseries",
   "description": "Each time series shows the 95th-percentile (the maximum latency for *most* requests)",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(loki_ingester_client_request_duration_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) != 0))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "# of Inflight Requests (read)",
   "type": "timeseries",
   "description": "Number of in-progress requests on the read path.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(route, method) (loki_inflight_requests{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",route=~\"loki_api_v1_index_stats|loki_api_v1_labels|loki_api_v1_query_range|/frontendv2pb.FrontendForQuerier/QueryResult\"})",
     "legendFormat": "{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "# of Inflight Requests (write)",
   "type": "timeseries",
   "description": "Number of in-progress requests on the write path.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum by(route, method) (loki_inflight_requests{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",route=~\"loki_api_v1_push|/logproto.Pusher/Push|/logproto.Querier/GetChunkIDs|/logproto.Querier/GetStats|/logproto.Querier/Label|/logproto.Querier/Query|/logproto.Querier/QuerySample|/logproto.Querier/GetStreamRates\"})",
     "legendFormat": "{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "# of Inflight Requests (backend)",
   "type": "timeseries",
   "description": "Number of in-progress requests on the backend path.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by(route, method) (loki_inflight_requests{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",route=~\"/schedulerpb.SchedulerForFrontend/FrontendLoop|/schedulerpb.SchedulerForQuerier/QuerierLoop\"})",
     "legendFormat": "{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of active readers",
     "type": "stat",
     "description": "Current number of clients connected to query-frontend.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "loki_querier_query_frontend_clients{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queried Logs",
     "type": "timeseries",
     "description": "Distribution of bytes processed per second for LogQL queries. It shows no data if nothing is reading from Loki.\n\nEach time series shows the 95th-percentile (the maximum data rate for *most* queries)",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])) by (le, juju_application))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index Query Requests",
     "type": "timeseries",
     "description": "Time spent in serving index query requests. It shows no data if nothing is reading from Loki.\n\nEach time series shows the 95th-percentile (the maximum data rate for *most* queries)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_index_request_duration_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Latency",
     "type": "timeseries",
     "description": "Each time series shows the 95th-percentile (the maximum latency for *most* requests)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, type) (rate(loki_logql_querystats_latency_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Latency (chunks)",
     "type": "timeseries",
     "description": "Distribution of the chunks download latency.\n\nEach time series shows the 95th-percentile (the maximum latency for *most* requests)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_logql_querystats_chunk_download_latency_seconds_bucket{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log lines / sec (per tenant)",
     "type": "timeseries",
     "description": "Log lines per second received for each tenant.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(tenant, juju_application) (rate(loki_distributor_lines_received_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval]))",
       "legendFormat": "{{juju_application}} / {{tenant}}"
      }
     ]
    },
    {
     "title": "Batch appends sent to ingesters / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_appends_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])",
       "legendFormat": "Successful"
      },
      {
       "expr": "loki_distributor_ingester_append_failures_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Blocks / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_blocks_per_chunk_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[5m])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_chunk_size_bytes_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_chunk_age_seconds_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_chunk_compression_ratio_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_chunk_encode_time_seconds_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, juju_application) (rate(loki_ingester_chunk_entries_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])))",
       "legendFormat": "{{juju_application}} (95th percentile)"
      }
     ]
    },
    {
     "title": "Chunks in Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "loki_ingester_memory_chunks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}",
       "legendFormat": "{{juju_application}}"
      }
     ]
    },
    {
     "title": "Chunks in Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(tenant, juju_application) (loki_ingester_memory_streams{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"})",
       "legendFormat": "{{juju_application}} / {{tenant}}"
      }
     ]
    },
    {
     "title": "Chunk Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])",
       "legendFormat": "create"
      },
      {
       "expr": "sum by(reason) (rate(loki_ingester_chunks_flushed_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval]))",
       "legendFormat": "flush / {{ reason }}"
      },
      {
       "expr": "sum by(fake) (rate(loki_ingester_chunks_stored_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval]))",
       "legendFormat": "stored"
      }
     ]
    },
    {
     "title": "Streams Stats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_streams_created_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])",
       "legendFormat": "create"
      },
      {
       "expr": "rate(loki_ingester_streams_removed_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", juju_charm=\"loki-k8s\"}[$__rate_interval])",
       "legendFormat": "delete"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Ahead Log (WAL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "What is the WAL?",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 138 },
     "options": {
      "content": "The **Write Ahead Log** (WAL) records incoming data and stores it temporarily in memory. \n\nIn the event of a crash, data will be recovered from the WAL."
     }
    },
    {
     "title": "WAL recovery rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_wal_recovered_bytes_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
       "legendFormat": "{{juju_application}}"
      }
     ]
    },
    {
     "title": "WAL write failures",
     "type": "timeseries",
     "description": "The rate of failures caused by a full disk.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_wal_disk_full_failures_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
       "legendFormat": "{{juju_application}}"
      }
     ]
    },
    {
     "title": "Data Recovery from WAL",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "loki_ingester_wal_replay_active{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction and Retention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Compaction (from restart)",
     "type": "stat",
     "description": "The time of the last compaction executed since the workload was last restarted",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compactions (rate)",
     "type": "timeseries",
     "description": "Total rate of tables compaction by status",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 148 },
     "targets": [
      {
       "expr": "rate(loki_boltdb_shipper_compact_tables_operation_total{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
       "legendFormat": "{{juju_unit}} ({{status}})"
      }
     ]
    },
    {
     "title": "Last Retention (from restart)",
     "type": "stat",
     "description": "The time of the last successful retention run since the workload was last restarted",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "loki_compactor_apply_retention_last_successful_run_timestamp_seconds{juju_application=~\"$juju_application\",juju_charm=\"loki-k8s\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}